services:
  flask:
    build: ./flask
    container_name: electric-diagnostic-stand-data-processor
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    volumes:
      - ./flask:/app
    environment:
      - FLASK_PORT=${FLASK_PORT}

  modbus:
    build: ./modbus
    container_name: electric-diagnostic-stand-frontend
    ports:
      - "${HOST_PORT}:${REACT_PORT}"
    environment:
      - REACT_PORT=${REACT_PORT}
      - HOST_PORT=${HOST_PORT}
    volumes:
      - ./modbus:/app
      - /app/node_modules  
    stdin_open: true
    tty: true
    depends_on:
      - flask
      - socket-server

  socket-server:
    build: ./server
    container_name: electric-diagnostic-stand-client
    ports:
      - "${SOCKET_PORT}:${SOCKET_PORT}" 
    environment:
      - SOCKET_PORT=${SOCKET_PORT}
    volumes:
      - ./server:/app
    command: ["node", "server.js"]
    depends_on:
      - flask
      
